### PR TITLE
fix: request Shizuku permissions only when necessary

### LINKED ISSUE #58: The denial of Shizuku permission sometimes leads to spam requests
Screen recorded showcase: https://github.com/vendetta-mod/VendettaManager/assets/86906143/51a557d2-a0c9-4d98-bf71-829bfb3e4859

Device: RMX3085
Android: 13
Shizuku: 13.5.3.r1036.fff3f87
Vendetta Manager: 1.1.0

I don't think it's a bug on Shizuku's side. I tested it with other apps with Shizuku permissions under the same conditions and there was no spamming. I know you've been diligently working on this integration for a single feature, but I just don't want unnecessary permissions.

Lastly, I want to thank the team behind Vendetta for keeping all those quality projects active and alive. And the plugins/themes community for their existence.

P.s. don't mind the bottom bar about Bluetooth eventually appearing, it's just Gadgetbridge complaining.

### PR DESCRIPTION
**Pull request by rushiiMachine**
Fixes #58

- Only request shizuku at startup if shizuku is the selected install method (not by default)
- Request and wait for shizuku perms again once installing and handle the event that permissions are denied/not available
- When switching install methods, check if shizuku is available and wait for permissions to be granted before confirming the change (previously this relied on shizuku was already granted at startup otherwise it disabled the switcher)

### CODE REVIEW

**Review by wingio — APPROVED** [review]

File: app/src/main/java/dev/beefers/vendetta/manager/ui/activity/MainActivity.kt [hunk 1]
```diff
@@ -38,8 +40,13 @@ class MainActivity : ComponentActivity() {
             )
         }
 
-        if (preferences.installMethod == InstallMethod.SHIZUKU)
-            ShizukuPermissions.requestShizukuPermissions()
+        if (preferences.installMethod == InstallMethod.SHIZUKU) {
+            lifecycleScope.launch {
+                if (!ShizukuPermissions.waitShizukuPermissions()) {
+                    preferences.installMethod = InstallMethod.DEFAULT
```
Comment (rushiiMachine) [inline app/src/main/java/dev/beefers/vendetta/manager/ui/activity/MainActivity.kt:46]: You should've probably shown a toast here otherwise it's changing a setting without telling the user
something like `R.string.msg_shizuku_denied`
